### ISSUE TITLE
Why does CLASS define a new global?

### ISSUE THREAD

**Issue by andersekdahl** [foam-framework/foam#294]
Since the code base is somewhat large, I haven't been able to fully grasp it. But I can't see any reason for the `CLASS` function to define a new global constructor, instead of just returning that constructor and let the user decide where to put it. The user can set it as a global, but could also assign it to `module.exports` or use ES6 `export` to expose it.

Is there something in FOAMs class system that makes this impossible?

**Comment by kgrgreer** [comment]
It only creates a global if you don't specify a package.  If you do something like:

CLASS({
   package: 'com.acme.foobar',
   name: 'MyModel',
   ...
});

Then it won't make a global.  Since the Model knows its intended package, we could possibly add optional support so that it automatically registers itself using your module system.

You can also just create the Model directly and then put it wherever you want.  Just do:

var MyModel = Model.create({
   name: 'MyModel',
   ...
});

This shows that Models are actually just normal Modelled objects themselves.  The CLASS() convenience method creates the Model and registers it in the appropriate package (although, it does this lazily once the Model is first referenced).
