### ISSUE TITLE
"Class" vs "Model"

### ISSUE THREAD

**Issue by jabowery** [foam-framework/foam#310]
Why:

CLASS(...
extendsModel
...)

Rather than:
MODEL(...
extendsModel
...)

or:

CLASS(...
extendsClass
...)

?

**Comment by shepheb** [comment]
`extends` and `class` are both reserved words in Javascript, so we avoid using them.

The original phrasing was `MODEL` and `extendsModel`. FOAM's models really are models, in the "modeling language" sense, but that's a very unfamiliar world to most programmers. The use of "class" in our docs and `CLASS` in code is hoping to make things more familiar.

Since we're doing metaprogramming at runtime in Javascript, it's harder to see the distinction. In our own discussions on the team, we tend to refer to the JSONish object you pass to `CLASS()` as the "model", which describes the "class". The "class" is what FOAM generates based on the model you provide, and the "prototype" is the Javascript prototype we actually create instances of.

For most purposes, though, there isn't much distinction between models and classes in this parlance. We wish we could use better syntax and spellings, but Javascript reserved lots of handy words and never used them.

As for why it isn't `CLASS` and `extendsClass` (and `class_` instead of `model_`) that's mostly historical. We added `CLASS` but didn't change "model" for "class" everywhere.

**Comment by shepheb** [comment]
We now use `extends` rather than `extendsModel`, which definitely helps this confusion. Closed either way; there's nothing actionable here.
